language: ruby
services:
  - redis-server
addons:
  postgresql: "9.6"
rvm: 2.6.4
cache: bundler
sudo: false
before_script:
  - psql -c 'create database foi_submissions_test;' -U postgres
  - cp config/database.yml-travis config/database.yml
before_install:
  - "echo '--colour' > ~/.rspec"
  - gem install bundler
  - gem update --system
install: bundle install
notifications:
  email: false
after_success:
  - ./script/build_and_push_to_ecr.sh
